# Quiz 1b

In [1]:
#pip install -U scikit-learn
from numpy import random
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score
import numpy as np

animals = ["cat", "dog", "squirrel", "cow", "sheep", "horse", "giraffe", "zebra", "lion", "tiger"]
numberOfLabels = 4

In [2]:
# Generate the ground truth numbers
GroundTruths=[]
i=0
while i<50:
    x = random.randint(1,numberOfLabels)
    GroundTruths.append(animals[x])
    i=i+1
#print(GroundTruths)


In [3]:
# Generate the prediction numbers
Predictions=[]
j=0
while j<50:
    x = random.randint(1,numberOfLabels)
    Predictions.append(animals[x])
    j=j+1
#print(Predictions)

In [4]:
# Get confusion matrix
confusionMatrix = confusion_matrix(GroundTruths, Predictions)
# Get F-measure
f1Score = f1_score(GroundTruths, Predictions, average='weighted')
# Get recall score
recallScore = recall_score(GroundTruths, Predictions, average='weighted')
# Get accuracy score
accuracyScore = accuracy_score(GroundTruths, Predictions)

print("Confusion Matrix:")
print(confusionMatrix)
print("\nF-Measure:")
print(f1Score)
print("\nRecall Score:")
print(recallScore)

Confusion Matrix:
[[2 6 7]
 [6 5 7]
 [7 7 3]]

F-Measure:
0.2

Recall Score:
0.2
