# Quiz 1b

In [1]:
pip install -U scikit-learn
from numpy import random
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, recall_score
import numpy as np

animalLabels = ["cat", "dog", "squirrel", "cow", "sheep", "horse", "giraffe", "zebra", "lion", "tiger"]
numberOfLabelsToUse = 4

In [2]:
# Generate the ground truth numbers
GroundTruths=[]
i=0
while i<50:
    x = random.randint(1,numberOfLabelsToUse)
    GroundTruths.append(animalLabels[x])
    i=i+1
#print(GroundTruths)


In [3]:
# Generate the prediction numbers
Predictions=[]
j=0
while j<50:
    x = random.randint(1,numberOfLabelsToUse)
    Predictions.append(animalLabels[x])
    j=j+1
#print(Predictions)

In [5]:
# Get confusion matrix
confusionMatrix = confusion_matrix(GroundTruths, Predictions)
# Get F-measure
f1Score = f1_score(GroundTruths, Predictions, average='weighted')
# Get recall score
recallScore = recall_score(GroundTruths, Predictions, average='weighted')
# Get accuracy score
accuracyScore = accuracy_score(GroundTruths, Predictions)

print("Confusion Matrix:")
print(confusionMatrix)
print("\nF-Measure:")
print(f1Score)
print("\nRecall Score:")
print(recallScore)
print("\nAccuracy Score:")
print(accuracyScore)

Confusion Matrix:
[[4 7 6]
 [7 8 2]
 [5 3 8]]

F-Measure:
0.39785281385281385

Recall Score:
0.4

Accuracy Score:
0.4


In [ ]:
#Conclusion:
#1 - As we decrease the number of classes/labels in the model, the predictions become more accurate
#2 - The number of samples does not affect the peformance of the model 